name= "ramen-api"
workers_dev = false

main = "src/index.ts"

routes = ["ramen-api.dev/*"]

compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[site]
bucket = "./content"

[vars]
ENV_BASE_URL = "https://ramen-api.dev/"
