name= "ramen-api"
workers_dev = false

main = "src/index.ts"

routes = ["ramen-api.dev/*"]

compatibility_date = "2023-03-01"

[site]
bucket = "./content"

[vars]
ENV_BASE_URL = "https://ramen-api.dev/"
